### ISSUE TITLE
issues with kalliope 0.6.0

### ISSUE THREAD

**Issue by Riseryn** [corus87/kodi-neuron#5]
Hello
I'm trying to use your neuron on kalliope version 0.6.0.
I have, actually, some troubles with two synapses.

firstly with kodi-start-movie
I, sometimes got this error :

File "resources/neurons/kodi/kodi.py", line 212, in MatchSearch
    located.append((item for item in results if item[lookingFor] == winner[0]).next())
AttributeError: 'generator' object has no attribute 'next'

it seems to appear mainly when the title contains spécial character like " : ", " - ", " & " or accentuated characters like " é " " à "
e.g blade:trinity

then kodi-play-artist

I got this error each time.
File "resources/neurons/kodi/kodi.py", line 858, in ListenToMusic
    if 'songs' in songs_result['result']:
KeyError: 'result'

thanks for your help

**Comment by corus87** [comment]
Hi, I just fixed the first issue.
In the next days, I'm gonna update this neuron and also try to fix the second  issue.

Thanks for reporting the issues.

**Comment by Riseryn** [comment]
Thanks for your quick answer.

**Comment by corus87** [comment]
I updated the neuron, can you please check if the second issue still occurs?

**Comment by Riseryn** [comment]
Hello
I've tested the new version 
excepted 

kodi-continue-on-second-kodi 
because i have only one instance

kodi-youtube-iss-live
the kodi plugin youtube is malfunctionning

4 neurons have problems

kodi-to-watch
    error 2 on kodi, share not available. must be from my config.

kodi-pvr-now
    File "resources/neurons/kodi/kodi.py", line 1102, in WhatIsRunning
    bc = all_bc['result']['broadcasts']
    KeyError: 'broadcasts'
I use
    pvr iptv simple client

 
kodi-play-song
    launch the song but after I got this error
    File "resources/neurons/kodi/kodi.py", line 979, in ListenToMusic
    if len(songs_array) > 1:
    TypeError: object of type 'NoneType' has no len()


kodi-play-radio
    don't find radio station in 'my favorite'
    I have 9

I also noticed that, after an order to kodi, sometimes kalliope freeze.
I have to reboot it.
I don't know if this comes from the programm or from kalliope. 

Hope this help you.
This is a great job.
With controls for navigation ( home, line up, line down, back, page up, page down etc..)
the programm will be perfect :)

**Comment by corus87** [comment]
The synapses are only examples, you can configure a lot by yourself. 

For the pvr, it should work with  the simple client too, if you have a working EPG.

Also play song should work too, if you have a working music library. 

For playing radio, you have to favorite an addon folder for example if you use this [Addon](https://kodi.wiki/view/Add-on:Radio), there you can put radio stations in "my stations", and this folder you can put in your favorites.

Like I set on the beginning, these are only examples, you can already do home,  back, page up etc.
Check the basic_action parameter and the link [provided](https://kodi.wiki/view/JSON-RPC_API/v8#Input.Action) there.

For example:

```
  - name: "kodi-go-up"
    signals:
      - order: "Go up"
    neurons:
      - kodi:
          basic_action: "up"

  - name: "kodi-go-home"
    signals:
      - order: "Go to home"
    neurons:
      - kodi:
          gui_window: "home"
```
What version of Kodi are you using? And on what platform?

**Comment by Riseryn** [comment]
Hi
Im using Kodi on a monitor (not the tv) Sony Bravia pro with android

**Comment by corus87** [comment]
So I assume you installed it from the playstore and got the newest version? 
But besides that I know it works with android.  
Can you show me your synapses and also the full stack trace when you try to play a song? 
And it would be nice if you use syntax highlight.  (copy the content in here, mark everything you want to highlight and press <> in the top bar. Then there should appear " ``` " of this at the beginning and the end, without the quotes)

**Comment by Riseryn** [comment]
Hello
thanks for your work and your help
With your explanation, its now ok for the radio.

here is the list of my synapses:.

```
  - name: "kodi-go-home"
    signals:
      - order: "accueil"
    neurons:
      - kodi:
          gui_window: "home"

  - name: "kodi-play-pause"
    signals:
      - order: "Pause kodi"        
    neurons:
      - kodi:
          basic_action: "pause"
          
  - name: "kodi-toggle-mute"
    signals:
      - order: "coupe le son"        
    neurons:
      - kodi:
          basic_action: "mute"                    

  - name: "kodi-volume-up"
    signals:
      - order: "monte le son"        
    neurons:
      - kodi:
          basic_action: "volumeup"
          
  - name: "kodi-volume-down"
    signals:
      - order: "baisse le son"        
    neurons:
      - kodi:
          basic_action: "volumedown"  

  - name: "kodi-stop-player"
    signals:
      - order: "arrête la lecture"
    neurons:
      - kodi:
          basic_action: "stop"
     
  - name: "kodi-play-player"
    signals:
      - order: "vitesse normale"
    neurons:
      - kodi:
          basic_action: "play"       

  - name: "kodi-up"
    signals:
      - order: "ligne précédente"
    neurons:
      - kodi:
          basic_action: "up"
          
  - name: "kodi-down"
    signals:
      - order: "ligne suivante"
    neurons:
      - kodi:
          basic_action: "down"

  - name: "kodi-pagedown"
    signals:
      - order: "page suivante"
    neurons:
      - kodi:
          basic_action: "pagedown"

  - name: "kodi-pageup"
    signals:
      - order: "page précédente"
    neurons:
      - kodi:
          basic_action: "pageup"

  - name: "kodi-select"
    signals:
      - order: "sélection"
    neurons:
      - kodi:
          basic_action: "select"

  - name: "kodi-back"
    signals:
      - order: "retour"
    neurons:
      - kodi:
          basic_action: "back"        
 
  - name: "kodi-left"
    signals:
      - order: "à gauche"
    neurons:
      - kodi:
          basic_action: "left"        
 
  - name: "kodi-right"
    signals:
      - order: "à droite"
    neurons:
      - kodi:
          basic_action: "right" 
 
  - name: "kodi-scrollup"
    signals:
      - order: "vers le haut"
    neurons:
      - kodi:
          basic_action: "scrollup"        
 
  - name: "kodi-scrolldown"
    signals:
      - order: "vers le bas"
    neurons:
      - kodi:
          basic_action: "scrolldown"
 
  - name: "kodi-fastforward"
    signals:
      - order: "avance rapide"
    neurons:
      - kodi:
          basic_action: "fastforward"
 
  - name: "kodi-rewind"
    signals:
      - order: "retour rapide"
    neurons:
      - kodi:
          basic_action: "rewind"
                  
  - name: "kodi-show-subs"
    signals:
      - order: "affiche sous-titre"       
    neurons:
      - kodi:
          basic_action: "showsubtitles"    
  
  - name: "kodi-seek-back-sec"
    signals:
      - order: "recul de {{ time }} secondes"
    neurons:
      - kodi:
          seek_backward: "{{ time }}"
          
  - name: "kodi-seek-forward-sec"
    signals:
      - order: "avance de {{ time }} secondes"
    neurons:
      - kodi:
          seek_forward: "{{ time }}"
          
  - name: "kodi-seek-for-min"
    signals:
      - order: "avance de {{ time }} minutes"
    neurons:
      - kodi:
          seek_forward: "{{ time }}"
          seek_unit: "minutes"
  
  - name: "kodi-seek-back-min"
    signals:
      - order: "recul de {{ time }} minutes"
    neurons:
      - kodi:
          seek_backward: "{{ time }}"
          seek_unit: "minutes"
          
  - name: "kodi-send-text"
    signals:
      - order: "envoie le texte à kodi {{ text_to_send }}"
    neurons:
      - kodi:
          send_text: "{{ text_to_send }}"  

  - name: "kodi-films"
    signals:
      - order: "montre les films"
    neurons:
      - kodi:
          show_video_path: "videodb://movies/titles" 
          
  - name: "kodi-epg"
    signals:
      - order: "guide tv"
    neurons:
      - kodi:
          show_window: "tvguide"  

        
  - name: "kodi-start-movie"
    signals:
      - order: 
          text: "lance le film {{ query }}"
          
    neurons:
      - kodi:
          movie: "{{ query }}"
          say_template: "{{ notfound }} n'a pas été trouvé"
          
  - name: "kodi-resume-lastwatched-tvshow"
    signals:
      - order: "reprend {{ tvshow }}"
    neurons:
      - kodi:
          tvshow: "{{ tvshow }}"
          tvshow_option: "resume_last_watched_show"
          say_template: "{{ notfound }} n'a pas été trouvé"

  - name: "kodi-resume-last-show"
    signals:
      - order: "continue dernier show"
    neurons:
      - kodi:
          tvshow_option: "continue_last_show"
          say_template: "{{ notfound }} n'a pas été trouvé"

         

  - name: "kodi-play-artist"
    signals:
      - order: 
          text: "joue la musique de {{ artist }}"
    neurons:  
      - kodi:
          artist: "{{ artist }}"
          say_template: "{{ notfound }} n'a pas été trouvé"

          
  - name: "kodi-play-genre"
    signals:
      - order: "joue style {{ genre }} "
    neurons:  
      - kodi:
          genre: "{{ genre }}"
          say_template: "{{ notfound }} n'a pas été trouvé"
             
  - name: "kodi-play-song-artist"
    signals:
      - order: "joue {{ song }} de  {{ artist }} "
    neurons:  
      - kodi:
          song: "{{ song }}"
          artist: "{{ artist }}"
          continue_with_artist: True
          say_template: "{{ notfound }} n'a pas été trouvé"

  - name: "kodi-play-song"
    signals:
      - order: "joue la chanson {{ song }}"
    neurons:  
      - kodi:
          song: "{{ song }}"
          say_template: "{{ notfound }} n'a pas été trouvé"
      
  - name: "kodi-play-radio"
    signals:
      - order: "joue la radio {{ channel }}"
    neurons:
      - kodi:
          favorite: "my stations"
          search_in_favorite: "{{ channel }}"
          add_to_playlist: True  
          say_template: "{{ notfound }} n'a pas été trouvé"
          
  - name: "kodi-pvr-now"
    signals:
      - order: "qu'est-ce qu'il y a sur {{ channel }}"
    neurons:
      - kodi:
          what_is_running: "current_on_tvchannel"
          channel: "{{ channel }}"
          file_template: "templates/kodi.j2"
        
  - name: "kodi-whats-running"
    signals:
      - order: "diffusées actuellement"
    neurons:
      - kodi:
          what_is_running: "current"
          file_template: "templates/kodi.j2"
```
and here the errors

kodi-play-song

```
Exception in thread <class 'kalliope.signals.order.order.Order'>:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/kalliope/signals/order/order.py", line 87, in run
    self.start_trigger()
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 405, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 1092, in _process
    self._transition_queue[0]()
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 423, in _trigger
    return self._process(event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 433, in _process
    if trans.execute(event_data):
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 283, in execute
    self._change_state(event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 294, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 140, in enter
    event_data.machine.callback(handle, event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 1037, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/signals/order/order.py", line 185, in analysing_order_thread
    is_api_call=False)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/SynapseLauncher.py", line 106, in run_matching_synapse_from_order
    execdata = lifo_buffer.execute(is_api_call=is_api_call)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/Lifo/LIFOBuffer.py", line 109, in execute
    self._process_synapse_list(last_synapse_fifo_list)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/Lifo/LIFOBuffer.py", line 139, in _process_synapse_list
    self._process_neuron_list(matched_synapse=matched_synapse)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/Lifo/LIFOBuffer.py", line 173, in _process_neuron_list
    parameters_dict=matched_synapse.parameters)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/NeuronLauncher.py", line 62, in start_neuron
    instantiated_neuron = NeuronLauncher.launch_neuron(neuron)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/NeuronLauncher.py", line 44, in launch_neuron
    resources_dir=neuron_folder)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/Utils/Utils.py", line 140, in get_dynamic_class_instantiation
    return klass(**parameters)
  File "resources/neurons/kodi/kodi.py", line 168, in __init__
    self.ListenToMusic()
  File "resources/neurons/kodi/kodi.py", line 980, in ListenToMusic
    if len(songs_array) > 1:
TypeError: object of type 'NoneType' has no len()

Erreur de segmentation
```
kodi-pvr-now ( I use pvr iptv simple client and tv catchup & more )

```
Exception in thread <class 'kalliope.signals.order.order.Order'>:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/kalliope/signals/order/order.py", line 87, in run
    self.start_trigger()
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 405, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 1092, in _process
    self._transition_queue[0]()
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 423, in _trigger
    return self._process(event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 433, in _process
    if trans.execute(event_data):
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 283, in execute
    self._change_state(event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 294, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 140, in enter
    event_data.machine.callback(handle, event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 1037, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/signals/order/order.py", line 185, in analysing_order_thread
    is_api_call=False)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/SynapseLauncher.py", line 106, in run_matching_synapse_from_order
    execdata = lifo_buffer.execute(is_api_call=is_api_call)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/Lifo/LIFOBuffer.py", line 109, in execute
    self._process_synapse_list(last_synapse_fifo_list)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/Lifo/LIFOBuffer.py", line 139, in _process_synapse_list
    self._process_neuron_list(matched_synapse=matched_synapse)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/Lifo/LIFOBuffer.py", line 173, in _process_neuron_list
    parameters_dict=matched_synapse.parameters)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/NeuronLauncher.py", line 62, in start_neuron
    instantiated_neuron = NeuronLauncher.launch_neuron(neuron)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/NeuronLauncher.py", line 44, in launch_neuron
    resources_dir=neuron_folder)
  File "/usr/local/lib/python3.7/dist-packages/kalliope/core/Utils/Utils.py", line 140, in get_dynamic_class_instantiation
    return klass(**parameters)
  File "resources/neurons/kodi/kodi.py", line 172, in __init__
    self.WhatIsRunning()
  File "resources/neurons/kodi/kodi.py", line 1103, in WhatIsRunning
    bc = all_bc['result']['broadcasts']
KeyError: 'broadcasts'

Erreur du bus
```

kodi-go-home
don't work.
tried with various option besides home (pictures, music..) no one works but no error in kalliope.

Hope this helps

**Comment by Riseryn** [comment]
some suggestions
volumeup and volumedown works but it just increase or decrease by one unit.
It would be cool to have a parameter to modify with a greater step.
Now the configuration is hard coded. it would be more user friendly, imo, to have a setting file.
continue the great job :)

**Comment by corus87** [comment]
My bad with the gui_window, its the wrong parameter, the right one is show_window.
```
  - name: "kodi-go-home"
    signals:
      - order: "Go to home"
    neurons:
      - kodi:
          show_window: "home"

```
I've fixed the readme with the right parameter. 

With the play-song I don't know whats wrong, but my guess would be, you don't have a proper music library, the songs need to be scanned by Kodi. 
You can maybe try this one:
```
  - name: "kodi-play-music"
    signals:
      - order: "play latest songs"
    neurons:  
      - kodi:
          lastplayed_songs: True

```
this should trigger the last 50 played songs on Kodi, if they are in your library. 

For the issue with the IPTV Simple Client, I have to setup this on my machine and look for myself what happens. But you do have a working EPG? 

I  think I can implement a simple volume control, something like `Kalliope --> set volume to 70 % `

**Comment by corus87** [comment]
I have added a volume control, you can give it a try. The range is from 0-100 
```
  - name: "kodi-set-volume"
    signals:
      - order: "Set volume to {{ volume }}"
    neurons:
      - kodi:
          host: 192.168.2.22
          set_volume_to: "{{ volume }}"
```

**Comment by Riseryn** [comment]
Hi, i have upgraded and installed the synapse kodi-set-volume"
when i said set volume to X
the command is send to kodi with no error in kalliope but the sound is stopped.
I have to manually change the volume to recover it.

**Comment by corus87** [comment]
Hmm that's strange...  Its working on my end with a clean Kalliope and a fresh installed Kodi...

**Comment by Riseryn** [comment]
My kodi is 18.5 Leia, all addons up to date.
What kind of information may be useful to you?

**Comment by corus87** [comment]
I have added a debug methode for the set_volume. 
Can you please start kalliope with `kalliope --debug` , ask kalliope to set volume to 80 and show me the whole debug output of this command.

**Comment by Riseryn** [comment]
I can't run kalliope -- debug, i got this
```
kalliope --debug
usage: kalliope [-h] [--run-synapse RUN_SYNAPSE] [--run-order RUN_ORDER]
                [--brain-file BRAIN_FILE] [--debug] [--git-url GIT_URL]
                [--neuron-name NEURON_NAME] [--stt-name STT_NAME]
                [--tts-name TTS_NAME] [--trigger-name TRIGGER_NAME]
                [--signal-name SIGNAL_NAME] [--deaf] [-v]
                action
kalliope: error: the following arguments are required: action
```

**Comment by corus87** [comment]
ah sorry, of course `kalliope start --debug`

**Comment by Riseryn** [comment]
I tried with the new version and the command is ok. But it seems the command is based on the current  level volume. if I say setvolume to 50 it setthe volume to 50% of the actual volume.
as far i'm concerned, it's totally fine for me

**Comment by Riseryn** [comment]
Strange, i tried the command mute after set volume and mute doesn't  respond even if i see in kalliope that the order is recognized and the signal send to kodi.
In factno other orders are executed even after a reboot.

**Comment by Riseryn** [comment]
ok i found the reason for non responding. I forgot to replace in kody.py localhost by the adress of my screen

**Comment by corus87** [comment]
I don't whats going on, on your end, but its not based on the current level volume, according to the [official API doc](https://kodi.wiki/view/JSON-RPC_API/v8#Application.SetVolume) (Which this neuron use) there is a minimum of 0 and maximum of 100. 
Your setup seems to be a bit strange for some reason xD

**Comment by Riseryn** [comment]
here the debug message
I skipped the part where kalliope search for a matching order
```
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [NeuronParameterLoader._associate_order_params_to_values] user order: mets le son à 80, order from synapse: mets le son à {{ volume }}
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [NeuronParameterLoader.get_parameters]Parameters for order: {'volume': '80'}
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [Cortex] place parameters in temp list: {'volume': '80'}
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [HookManager] calling synapses in hook name: on_order_found
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [HookManager] hook: on_order_found , type: <class 'NoneType'>
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [SynapseLauncher] start_synapse_by_list_name called with synapse list: None 
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [LIFOBuffer] Add a new synapse list to process to the LIFO
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [LIFOBuffer] number of synapse list to process: 1
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [LIFOBuffer] number of neuron to process: 1
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [LIFOBuffer] process_neuron_list: is_api_call: False
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [NeuronLauncher] replacing brackets from {'host': '192.168.1.10', 'set_volume_to': '{{ volume }}', 'is_api_call': False}, using {'volume': '80'}
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [NeuronLauncher] replacing brackets from 192.168.1.10, using {'volume': '80'}
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [NeuronLauncher] replacing brackets from {{ volume }}, using {'volume': '80'}
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [NeuronLauncher] replacing brackets from False, using {'volume': '80', 'name': 'Alain', 'kalliope_memory': {'kalliope_last_tts_message': "Je n'ai pas saisi cet ordre", 'kalliope_last_order': 'mets le son à 80'}}
2020-03-03 17:50:48 :: kalliope-0.6.1 :: Run neuron: "{'name': 'kodi', 'parameters': {'host': '192.168.1.10', 'set_volume_to': '80', 'is_api_call': False}}"
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [Utils]-> get_dynamic_class_instantiation : package path : kalliope.neurons.kodi.kodi
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [Utils]-> get_dynamic_class_instantiation : loading path : resources/neurons/kodi/kodi.py, as package Kodi
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [NeuronModule] TTS args: {'name': 'pico2wave', 'parameters': {'language': 'fr-FR', 'samplerate': 44100, 'cache': True}}
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [ Kodi debug ] set_volume is 80  
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [LIFOBuffer] complete mode
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [Cortex] Clean temp memory
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [HookManager] calling synapses in hook name: on_processed_synapses
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [HookManager] hook: on_processed_synapses , type: <class 'NoneType'>
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [SynapseLauncher] start_synapse_by_list_name called with synapse list: None 
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [Order] Entering state: start_order_listener
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [HookManager] calling synapses in hook name: on_start_listening
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [HookManager] hook: on_start_listening , type: <class 'NoneType'>
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [SynapseLauncher] start_synapse_by_list_name called with synapse list: None 
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [OrderListener] running ...
2020-03-03 17:50:48 :: kalliope-0.6.1 :: [Order] Entering state: waiting_for_order_listener_callback
```

**Comment by Riseryn** [comment]
Maybe the cause comes not from kodi but from the monitor and the way it handles sound.
From kodi the level volume is correctly handheld within its parameters but the output is managed by the monitor

**Comment by corus87** [comment]
hmm looks normal to me... So if you change the volume, its still happen that the volume of the neuron depends on the current volume in Kodi? 
I think there is something wrong with your Kodi config. You could try to start a new profile, just for testing rename the[ .kodi folder](https://kodi.wiki/view/Userdata) to something like .kodi.backup and start Kodi and try again.

I don't think the cause comes from you monitor, because it should only change the volume in Kodi itself. Also on my setup, the sounds comes from a AVR and if I change the volume with the neuron, it changes only in Kodi itself.  
Also on my Android phone, Kodi volumes works as expected.

**Comment by corus87** [comment]
Feel free to reopen.
